language: julia
dist: trusty
sudo: true
os:
  - linux
  - osx
julia:
  - 1.0
  - 0.7
  - nightly
notifications:
  email: false
env:
  - DOCUMENTER_DEBUG="true" CONDA_JL_VERSION="2" PYTHON=""
script:
  - julia -e 'using Pkg; Pkg.activate(pwd())'
  - julia -e 'using Pkg; Pkg.update()'
  - julia -e 'using Pkg; Pkg.resolve()'
  - julia -e 'using Pkg; Pkg.build("Omega")'
  - julia -e 'using Pkg; Pkg.add("Test")'
  - julia --depwarn=no -e 'using Pkg; Pkg.test("Omega", coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
