language: julia
dist: trusty
sudo: true
os:
  - linux
  - osx
julia:
  # - 0.7
  - nightly
notifications:
  email: false
env:
  - DOCUMENTER_DEBUG="true" CONDA_JL_VERSION="2" PYTHON=""
script:
  - julia -e 'Pkg.clone("https://github.com/zenna/Spec.jl")'
  - julia -e 'Pkg.add("UnicodePlots")'
  - julia -e 'Pkg.add("ForwardDiff")'
  - julia -e 'Pkg.add("Flux")'
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Omega")'
  - julia -e 'Pkg.test("Omega", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Omega")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Omega")); include(joinpath("docs", "make.jl"))'
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
