site_name:        Mu.jl
repo_url:         https://github.com/zenna/Mu.jl
site_description: A miniminal but powerful causal probabilistic programming languagie
site_author:      zenna

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
